flowchart TD
початок:::перший_клас
задати_запитання>користувач_вводить_відповідь]:::другий_клас
показати_інструкції:::третий_клас
кінець_програми:::четвертий_клас


початок-->показати_інструкції
показати_інструкції-->задати_запитання

задати_запитання--вихід--> кінець_програми
задати_запитання--допомога--> показати_довідку
задати_запитання--42--> Вітаю!
задати_запитання--інше-->показати_інструкції


показати_довідку --> показати_інструкції
Вітаю! --> кінець_програми

classDef перший_клас fill:#4040ff
classDef другий_клас fill:#800000
classDef третий_клас fill:#208090
classDef четвертий_клас fill:#6600aa


flowchart TD

початок --> отримати_час_доби>отримати час доби]
отримати_час_доби --> 6_11{між 6 і 11?}
6_11 --|ні|--> 11_14{між 11 і 14?}
6_11 --|так|--> доброго_ранку[/доброго ранку/]
11_14 --|ні|-->14_18{ між  14 і 18?}
11_14 --|так|--> доброго_дня[/доброго дня/]
14_18 --|ні|-->18_21{ між 18 і 21?}
14_18 --|так|-->доброго_вечора[/доброго вечора/]
18_21 --|ні|-->доброї_ночі[/доброї ночі/]
18_21 --|так|-->доброго_вечора[/доброго вечора/]


